
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int immediate = 4;
  public static final int variable = 9;
  public static final int operation = 3;
  public static final int EOF = 0;
  public static final int separator = 2;
  public static final int segment = 5;
  public static final int string = 7;
  public static final int types = 8;
  public static final int error = 1;
  public static final int label = 6;
  public static final int register = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "separator",
  "operation",
  "immediate",
  "segment",
  "label",
  "string",
  "types",
  "variable",
  "register"
  };
}

